### ISSUE TITLE
Website www.ekesete.net seems to be down

### ISSUE THREAD

**Issue by ngsimon** [ichinomoto/dm200_tools#2]
Hello,

The website http://www.ekesete.net/ and the DM200/250 download links seem to be down.
Would it be possible to troubleshoot ?

Thank you,

**Comment by ichinomoto** [comment]
Host server of my site was down. 
Still can't open this URL?
https://www.ekesete.net/log/?p=9504

**Comment by ngsimon** [comment]
Thank you, it works now !
